BEGIN;
CREATE DATABASE IF NOT EXISTS Junkyard;
USE Junkyard;

CREATE TABLE LISTING (
	
    LISTING_ID INT PRIMARY KEY,
    LISTING_LOT INT,
    LISTING_DATE DATE,
    LISTING_VIN VARCHAR(45),
    LISTING_EXT_COLOR VARCHAR(45),
    LISTING_INT_COLOR VARCHAR(45),
    CAR_ID INT REFERENCES CAR(CAR_ID),
    ENGINE_ID INT REFERENCES ENGINE(ENGINE_ID),
    LISTING_PARTS_LISTING_ID INT
    
);

CREATE TABLE CAR(

CAR_ID INT PRIMARY KEY,
CAR_MAKE VARCHAR(45),
CAR_MODEL VARCHAR(45),
CAR_YEAR INT,
CAR_CHAS_CODE VARCHAR(45),
ENGINE_ID INT REFERENCES ENGINE(ENGINE_ID)


);

CREATE TABLE ENGINE(

ENGINE_ID INT PRIMARY KEY REFERENCES LISTING(ENGINE_ID),
ENGINE_MAKE VARCHAR(45),
ENGINE_MODEL VARCHAR(45),
ENGINE_TYPE VARCHAR(45),
ENGINE_ASP VARCHAR(45),
ENGINE_SIZE VARCHAR(45)

);

CREATE TABLE LISTING_PARTS(
LISTING_ID INT PRIMARY KEY REFERENCES LISTING(LISTING_ID),
PART_ID INT REFERENCES PART(PART_ID)

);

CREATE TABLE PART(

PART_ID INT PRIMARY KEY,
PART_NAME VARCHAR(45),
PART_PARICE INT,
PART_TYPE VARCHAR(45)

);